name: animeflix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Navigation externe (ouvrir Google, Sekai.one, etc.)
  url_launcher: ^6.3.0

  # IcÃ´nes Cupertino (style iOS)
  cupertino_icons: ^1.0.8

  # RequÃªtes HTTP (API Jikan)
  http: ^1.2.2

  # Lecture vidÃ©o (MP4 / streaming)
  video_player: ^2.9.2

  # Lecteur vidÃ©o avec contrÃ´les (optionnel)
  chewie: ^1.8.1

  # ğŸµ Jouer des sons (Splash, effets)
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # GÃ©nÃ©rateur dâ€™icÃ´nes dâ€™application
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/sounds/

# ğŸ”¥ Configuration pour gÃ©nÃ©rer lâ€™icÃ´ne de lâ€™app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/animeflix.png"  # Ton logo ici
  min_sdk_android: 21
